-----------------------------------------------
-- gpuCode functions (use PrintTable)

gpuCode = method()
gpuCode (GateMatrix,GateMatrix,File):= (M,I,f) -> gpuCode(flatten entries M, flatten entries I,f)
gpuCode (List,List,File) := (outputs,inputs,f) -> (
    h := newPrintTable " = ";
    scan(inputs, g->printName(g,h));
    scan(outputs, g->printName(g,h));
    f << "__kernel void evaluateSLPonGPUs(__global float* data,__global float* output) {
    uint global_addr_input = get_global_id(0) * " << #inputs << ";
    uint global_addr_output = get_global_id(0) * " << #outputs << ";" << endl;
    f <<"    float " << concatenate between(",",apply(#inputs,i->"X"|i)) << ";" << endl;
    scan(h#"#vars", i -> f << ("    X"|i|" = data[global_addr_input+"|i|"];") << endl);
    scan(h#"#lines", i -> f << "    float " << h#i << ";" << endl);
    scan(#outputs, i-> f << ("    output[global_addr_output+"|i|"] = "|printName(outputs#i,h)|";") << endl); 
    f << "}" << endl;
    )
gpuCode (GateMatrix,GateMatrix) := (M,I) -> gpuCode(flatten entries M, flatten entries I)
gpuCode (List,List) := (outputs,inputs) -> gpuCode(outputs,inputs,stdio)


-* The following needs to be generated by along with `gpuCode`
#define PROGRAM_FILE "determinant.cl"
#define KERNEL_FUNC "evaluateSLPonGPUs"

#define NUM_INPUTS 4
#define NUM_OUTPUTS 1
#define NUM_EVALUATIONS 100
#define INPUT_ARRAY_SIZE NUM_EVALUATIONS*NUM_INPUTS
#define OUTPUT_ARRAY_SIZE NUM_EVALUATIONS*NUM_OUTPUTS

int main() {

   /* OpenCL structures */
   cl_device_id device;
   cl_context context;
   cl_program program;
   cl_kernel kernel;
   cl_command_queue queue;
   cl_int i, j, err;
   size_t local_size = 1;
   size_t global_size;

   
   /* Create device and context 

   Creates a context containing only one device — the device structure 
   created earlier.
   */
   device = create_device();
   context = clCreateContext(NULL, 1, &device, NULL, NULL, &err);
   if(err < 0) {
      perror("Couldn't create a context");
      exit(1);   
   }

   /* Build program */
   program = build_program(context, device, PROGRAM_FILE);

   /* Data and buffers    */
   float data[INPUT_ARRAY_SIZE];
   float output[OUTPUT_ARRAY_SIZE];
   cl_mem input_buffer, output_buffer;
   cl_int num_groups;

   /* Initialize data */
   for(i=0; i<INPUT_ARRAY_SIZE; i++) {
      data[i] = 1.0f*i*i;
   }

   /* Create data buffer 

   • `global_size`: total number of work items that will be 
      executed on the GPU (e.g. total size of your array)
   • `local_size`: size of local workgroup. Each workgroup contains 
      several work items and goes to a compute unit 

   In this example, the kernel is executed by eight work-items divided into 
   two work-groups of four work-items each. Returning to my analogy, 
   this corresponds to a school containing eight students divided into 
   two classrooms of four students each.   

     Notes: 
   • Intel recommends workgroup size of 64-128. Often 128 is minimum to 
   get good performance on GPU
   • On NVIDIA Fermi, workgroup size must be at least 192 for full 
   utilization of cores
   • Optimal workgroup size differs across applications
   */
   global_size = NUM_EVALUATIONS;
   num_groups = global_size/local_size;
   input_buffer = clCreateBuffer(context, CL_MEM_READ_ONLY |
         CL_MEM_COPY_HOST_PTR, INPUT_ARRAY_SIZE * sizeof(float), data, &err); // <=====INPUT
   output_buffer = clCreateBuffer(context, CL_MEM_READ_WRITE |
         CL_MEM_COPY_HOST_PTR, OUTPUT_ARRAY_SIZE * sizeof(float), output, &err); // <=====OUTPUT
   if(err < 0) {
      perror("Couldn't create a buffer");
      exit(1);   
   };

   /* Create a command queue 

   Does not support profiling or out-of-order-execution
   */
   queue = clCreateCommandQueue(context, device, 0, &err);
   if(err < 0) {
      perror("Couldn't create a command queue");
      exit(1);   
   };

   /* Create a kernel */
   kernel = clCreateKernel(program, KERNEL_FUNC, &err);
   if(err < 0) {
      perror("Couldn't create a kernel");
      exit(1);
   };

   /* Create kernel arguments */
   err = clSetKernelArg(kernel, 0, sizeof(cl_mem), &input_buffer); // <=====INPUT
   err |= clSetKernelArg(kernel, 1, sizeof(cl_mem), &output_buffer); // <=====OUTPUT
   if(err < 0) {
      perror("Couldn't create a kernel argument");
      exit(1);
   }

   /* Enqueue kernel 

   At this point, the application has created all the data structures 
   (device, kernel, program, command queue, and context) needed by an 
   OpenCL host application. Now, it deploys the kernel to a device.

   Of the OpenCL functions that run on the host, clEnqueueNDRangeKernel 
   is probably the most important to understand. Not only does it deploy 
   kernels to devices, it also identifies how many work-items should 
   be generated to execute the kernel (global_size) and the number of 
   work-items in each work-group (local_size).
   */
   err = clEnqueueNDRangeKernel(queue, kernel, 1, NULL, &global_size, 
         &local_size, 0, NULL, NULL); 
   if(err < 0) {
      perror("Couldn't enqueue the kernel");
      std::cerr << err << std::endl;
      exit(1);
   }

   /* Read the kernel's output    */
   err = clEnqueueReadBuffer(queue, output_buffer, CL_TRUE, 0, 
         sizeof(output), output, 0, NULL, NULL); // <=====GET OUTPUT
   if(err < 0) {
      perror("Couldn't read the buffer");
      exit(1);
   }

   for (int i=0; i < NUM_EVALUATIONS; i++)
     std::cout << i << " => " << output[i] << std::endl;  
   
   /* Deallocate resources */
   clReleaseKernel(kernel);
   clReleaseMemObject(output_buffer);
   clReleaseMemObject(input_buffer);
   clReleaseCommandQueue(queue);
   clReleaseProgram(program);
   clReleaseContext(context);
   return 0;
}

*-